# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 12:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0007_auto_20190528_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='count',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='category',
        ),
        migrations.AddField(
            model_name='vote',
            name='content',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='vote',
            name='design',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='vote',
            name='usability',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
